version: '3'
services:
  app:
    build:.
    # Montamos el directorio actual (.) en /usr/src/app dentro del contenedor
    # Esto permite editar c√≥digo en VS Code y verlo reflejado en la app
    volumes:
      -.:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/taller_db
    # Usamos nodemon o node directo. El comando se sobreescribe para mantener el contenedor vivo
    command: /bin/sh -c "while sleep 1000; do :; done"

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
